<?php
    define("RootFolder",__DIR__);
    date_default_timezone_set('Europe/London'); 
    IncludeTools();
    session_start();
    $debug=TRUE;
    set_time_limit(500);
    if($debug==TRUE)
    {
        error_reporting(E_ALL);
        ini_set('display_errors', 'On');
    }

    function GetRootFolder()
    {
        return constant("RootFolder");
    }

    function HeaderImports()
    {
        echo '<link rel="shortcut icon" type="image/png" href="favicon.png"/>';
        echo '<link rel="manifest" href="/manifest.json">';
        $files = scandir(GetRootFolder().'/library/css');
        foreach($files as $file)
        {
            if(strpos($file,".css")!==false)
            {
                echo "<link rel='stylesheet' href='library/css/".$file."'/>";
            }
        }

        $files = scandir(GetRootFolder().'/library/js');
        foreach($files as $file)
        {
            if(strpos($file,".js")!==false)
            {
                echo "<script src='library/js/".$file."' integrity='".GetHash(GetRootFolder().'/js'.$file)."' crossorigin='anonymous'></script>";
            }
        }

        $files = scandir(GetRootFolder().'/css');
        foreach($files as $file)
        {
            if(strpos($file,".css")!==false)
            {
                echo "<link rel='stylesheet' href='css/".$file."'/>";
            }
        }

        $files = scandir(GetRootFolder().'/js');
        foreach($files as $file)
        {
            if(strpos($file,".js")!==false)
            {
                echo "<script src='js/".$file."' integrity='".GetHash(GetRootFolder().'/js'.$file)."' crossorigin='anonymous'></script>";
            }
        }
    }

    function IncludeTools()
    {
        $files = scandir(GetRootFolder().'/tools');
        foreach($files as $file)
        {
            if(strpos($file,".php")!==false)
            {
                include(GetRootFolder()."/tools/".$file);
            }
        }
    }


    //For crossorigin importing for the js scripts
    function GetHash($file)
    {
        try
        {
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, $file);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                //echo 'Error:' . curl_error($ch);
                $result = "";
            }
            curl_close ($ch);
            return $result;
        }
        catch(Exception $e)
        {
            echo "<script>console.log('"+$e->getMessage()+"');</script>";
            return "";
        }
    }

    function gen_uuid() {
        return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            // 32 bits for "time_low"
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),
    
            // 16 bits for "time_mid"
            mt_rand( 0, 0xffff ),
    
            // 16 bits for "time_hi_and_version",
            // four most significant bits holds version number 4
            mt_rand( 0, 0x0fff ) | 0x4000,
    
            // 16 bits, 8 bits for "clk_seq_hi_res",
            // 8 bits for "clk_seq_low",
            // two most significant bits holds zero and one for variant DCE1.1
            mt_rand( 0, 0x3fff ) | 0x8000,
    
            // 48 bits for "node"
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
        );
    }

    function getDayOfWeekString($dayOfWeekNumber)
    {
        if($dayOfWeekNumber!=null)
        {
            $days = [
                0 => 'Sunday',
                1 => 'Monday',
                2 => 'Tuesday',
                3 => 'Wednesday',
                4 => 'Thursday',
                5 => 'Friday',
                6 => 'Saturday'
              ];
            $dayOfWeek = $days[$dayOfWeekNumber];
            return $dayOfWeek;
        }
        else
        {
            return "";
        }
    }
?>