SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `scheduleManager` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `scheduleManager`;

DROP TABLE IF EXISTS `Tasks`;
CREATE TABLE IF NOT EXISTS `Tasks` (
  `ID` int(255) NOT NULL AUTO_INCREMENT,
  `GUID` varchar(255) NOT NULL,
  `Description` varchar(255) NOT NULL,
  `Repeat` tinyint(1) NOT NULL,
  `RepeatRate` varchar(255) NOT NULL,
  `Date` date NOT NULL,
  `DayOfWeek` varchar(255) NOT NULL,
  `Hour` time NOT NULL,
  `UserGUID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GUID` (`GUID`),
  KEY `FK_UserGUID` (`UserGUID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `Users`;
CREATE TABLE IF NOT EXISTS `Users` (
  `ID` int(255) NOT NULL AUTO_INCREMENT,
  `GUID` varchar(255) NOT NULL,
  `Username` varchar(255) NOT NULL,
  `Password` varchar(255) NOT NULL,
  `Email` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GUID` (`GUID`),
  UNIQUE KEY `Email` (`Email`),
  UNIQUE KEY `[USERNAME]` (`Username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


DROP TRIGGER IF EXISTS `before_insert_users`;
DELIMITER $$
CREATE TRIGGER `before_insert_users` BEFORE INSERT ON `Users` FOR EACH ROW BEGIN
  IF new.GUID IS NULL THEN
    SET new.GUID = uuid();
  END IF;
END
$$
DELIMITER ;


ALTER TABLE `Tasks`
  ADD CONSTRAINT `FK_UserGUID` FOREIGN KEY (`UserGUID`) REFERENCES `Users` (`GUID`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;